[package]
authors = ["Mikail Khan <mikail.khan45@gmail.com>"]
edition = "2018"
name = "mathlang"
version = "0.1.0"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"

num = "0.3.1"

tempfile = "3.2.0"
pandoc = "0.8"

notify = "4.0.15"

lazy_static = "1.4.0"

bimap = "0.6.0"

rug = "1.11.0"
